/**
 * 癒見幸福 · 魔法占星學院
 * 線上占卜大典卡牌全庫 (Divination Cards Complete Database)
 * 包含：經典偉特塔羅 78 張 (大阿卡納 22 + 小阿卡納 56)、雷諾曼 36 張
 * 全卡牌注入【江戶浮世繪木版畫 (Ukiyo-e)】美學意象與愛倫院長生活魔藥處方
 * 100% 繁體中文（台灣）· Zero Attribution
 */

(function (global) {
  'use strict';

  const TAROT_CARDS = [
  {
    "id": "t_00",
    "name": "0. 愚者 (The Fool)",
    "ukiyoName": "浮世浪人",
    "element": "風",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "雲遊四海的浪人行者，站在富士絕頂崖邊，心懷純真信任，邁向未知江湖。",
    "reversed": "輕率魯莽、恐懼未知、缺乏防備。提醒暫停狂奔，審視足下深淵。",
    "potion": "迷迭香精油 + 白水晶，賦予清澈無畏的赤子勇氣。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【浮世浪人】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_01",
    "name": "I. 魔術師 (The Magician)",
    "ukiyoName": "陰陽術師",
    "element": "風",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "江戶天才陰陽咒術師，桌上陳列劍鏡符印，天地要素齊備，化虛為實的顯化之神。",
    "reversed": "賣弄幻術、注意力渙散、承諾空泛。提醒回歸真實本質，莫以巧言自欺。",
    "potion": "薄荷精油 + 黃水晶，聚精會神，打開顯化神諭之門。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【陰陽術師】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_02",
    "name": "II. 女祭司 (The High Priestess)",
    "ukiyoName": "御神水巫",
    "element": "水",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "深居神社幽境的巫女，手持古卷靜默觀照，直覺如古井深潭般清澈澄明。",
    "reversed": "情緒鬱結、直覺蔽塞、孤立冷漠。提醒打開心扉，接納感性潮汐的湧動。",
    "potion": "真正薰衣草精油 + 月光石，沉靜心靈微瀾，連結潛意識智慧。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【御神水巫】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_03",
    "name": "III. 皇后 (The Empress)",
    "ukiyoName": "豐饒之姬",
    "element": "土",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "盛裝端坐於櫻花林下的貴族姬樣，萬物萌發生機，母性慈愛與感官豐盛。",
    "reversed": "過度溺愛、自我耗竭、創造力停滯。提醒劃定心靈邊界，先滋養自我。",
    "potion": "大馬士革玫瑰精油 + 粉晶，喚醒深層自愛與大地豐盛共振。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【豐饒之姬】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_04",
    "name": "IV. 皇帝 (The Emperor)",
    "ukiyoName": "征夷將軍",
    "element": "火",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "端坐天守閣之征夷大將軍，威儀莊嚴、法令森嚴，以鐵腕秩序開拓太平盛世。",
    "reversed": "專斷剛愎、掌控焦慮、缺乏彈性。提醒放下過度戒心，學會信任同袍。",
    "potion": "雪松精油 + 紅瑪瑙，定錨核心中軸，展現沉穩王者魄力。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【征夷將軍】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_05",
    "name": "V. 教皇 (The Hierophant)",
    "ukiyoName": "高僧大師",
    "element": "土",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "古剎金堂內傳道解惑之高僧，承繼千年正法戒律，引領迷途靈魂尋得歸宿。",
    "reversed": "教條桎梏、墨守成規、迷信權威。勇敢質疑僵化教條，探尋自性之光。",
    "potion": "乳香精油 + 青金石，開啟靈性領悟，接引正向智者指引。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【高僧大師】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_06",
    "name": "VI. 戀人 (The Lovers)",
    "ukiyoName": "連理交杯",
    "element": "風",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "櫻花紛落下的合掌誓約，靈魂深處的和諧共振與神聖價值抉擇。",
    "reversed": "價值衝突、分歧猜疑、誘惑迷失。回歸本心核心標準，重拾真摯承諾。",
    "potion": "依蘭精油 + 紅紋石，點亮心輪溫暖，吸引同頻靈魂相遇。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【連理交杯】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_07",
    "name": "VII. 戰車 (The Chariot)",
    "ukiyoName": "甲冑武將",
    "element": "水",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "身披黑紅甲冑的先鋒大將，駕馭烈馬衝破敵陣，以堅定意志奪取勝局。",
    "reversed": "失控狂躁、橫衝直撞、後力不繼。收緊韁繩深呼吸，校正前進航道。",
    "potion": "黑胡椒精油 + 赤鐵礦，激發勇猛魄力，劈波斬浪克敵制勝。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【甲冑武將】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_08",
    "name": "VIII. 力量 (Strength)",
    "ukiyoName": "馴獅姬",
    "element": "火",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "素手撫摸狂暴神獸的柔弱姬君，以無邊慈悲融化暴戾，展現至高無上的溫柔韌性。",
    "reversed": "自我懷疑、暴躁失控、耐性告罄。溫和對待挫敗中的自己，以柔克剛。",
    "potion": "天竺葵精油 + 太陽石，平衡意志神經叢，點燃持久溫和的恆心。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【馴獅姬】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_09",
    "name": "IX. 隱士 (The Hermit)",
    "ukiyoName": "竹林幽客",
    "element": "土",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "提燈獨行於幽深雪夜的修道隱者，向內探尋本真自性，在孤獨中凝練真知。",
    "reversed": "孤芳自賞、逃避塵世、心門緊閉。適度向值得信任的知己分享靈魂微光。",
    "potion": "岩蘭草精油 + 黑曜石，深扎大地根基，在靜默中尋得定見。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【竹林幽客】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_10",
    "name": "X. 命運之輪 (Wheel of Fortune)",
    "ukiyoName": "浮世法輪",
    "element": "火",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "江戶海潮之上旋轉之命運水車，盛衰流轉，順應天地時序迎來撥雲見日。",
    "reversed": "抗拒無常、徒勞掙扎、故步自封。看透成敗循環本質，順水推舟乘勢而起。",
    "potion": "佛手柑精油 + 綠幽靈，轉動幸運齒輪，接納生命順流恩典。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【浮世法輪】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_11",
    "name": "XI. 正義 (Justice)",
    "ukiyoName": "明鏡法官",
    "element": "風",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "明鏡高懸之奉行所裁判長，手持天秤與寶劍，因果明察秋毫，客觀公正。",
    "reversed": "偏頗苛責、是非顛倒、推卸責任。放下主觀偏見，誠實面對自作自受之因果。",
    "potion": "尤加利精油 + 螢石，驅散雜念迷霧，維繫心靈天秤的和諧。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【明鏡法官】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_12",
    "name": "XII. 倒吊人 (The Hanged Man)",
    "ukiyoName": "松枝懸客",
    "element": "水",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "倒懸於千丈松枝上的求道行者，主動臣服反向視角，在靜止中參透天地玄機。",
    "reversed": "無謂犧牲、自憐抱怨、卡關抗拒。主動解開腳踝繩索，換個角度豁然開朗。",
    "potion": "絲柏精油 + 海藍寶，釋放緊繃執著，轉化生命困頓視角。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【松枝懸客】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_13",
    "name": "XIII. 死神 (Death)",
    "ukiyoName": "櫻吹雪",
    "element": "水",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "落櫻滿天下的送行死神，落葉歸根入土成泥，象徵徹底告別舊章、孕育新生。",
    "reversed": "緊抓不放、懼怕告別、苟延殘喘。勇敢對枯萎的過去道別，迎向朝霞曙光。",
    "potion": "沒藥精油 + 透石膏，淨化舊有沉重印記，迎接心靈鳳凰涅槃。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【櫻吹雪】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_14",
    "name": "XIV. 節制 (Temperance)",
    "ukiyoName": "茶道宗師",
    "element": "火",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "水火交融的茶道大師，提壺注水從容優雅，將極端衝突調和為無上甘露。",
    "reversed": "失衡失控、暴飲暴食、焦躁極端。暫停外在過度刺激，回歸自然調和節奏。",
    "potion": "羅馬洋甘菊精油 + 紫水晶，撫平激動波瀾，調和身心泉源。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【茶道宗師】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_15",
    "name": "XV. 惡魔 (The Devil)",
    "ukiyoName": "般若魅影",
    "element": "土",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "暗夜神社簷下的般若魅影，照見內心深處的貪婪執念與作繭自縛之虛妄鏈條。",
    "reversed": "擺脫誘惑、打破心魔、重獲自由。勇敢認清不再為你服務的執念，解鎖手銬。",
    "potion": "廣藿香精油 + 茶晶，淨化沉濁雜質，扎實保護個人能量場。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【般若魅影】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_16",
    "name": "XVI. 高塔 (The Tower)",
    "ukiyoName": "天雷天守",
    "element": "火",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "狂風暴雨中天雷擊裂金箔天守閣，幻象摧毀之時，正是真理重光奠基之日。",
    "reversed": "掩耳盜鈴、逃避破局、積弊難返。欣然接納震盪洗禮，在瓦礫堆中重建真我。",
    "potion": "茶樹精油 + 虎眼石，穩定驚魂未定的心神，在破局中重獲生機。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【天雷天守】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_17",
    "name": "XVII. 星星 (The Star)",
    "ukiyoName": "天河明珠",
    "element": "風",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "雨過天晴夜空下的七夕織女，手傾神露入清溪，星辰指路，心願正被宇宙應許。",
    "reversed": "希望幻滅、懷疑迷茫、灰心喪志。請相信北辰星宿永恆閃耀，耐心守候拂曉。",
    "potion": "橙花精油 + 天河石，喚醒心靈希望之泉，注入安詳寧靜。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【天河明珠】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_18",
    "name": "XVIII. 月亮 (The Moon)",
    "ukiyoName": "朧月夜",
    "element": "水",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "薄霧籠罩的古城池畔，朧月倒映水中，照見潛意識中的浮躁恐懼與暗湧波濤。",
    "reversed": "迷霧漸散、真相大白、恐懼消退。看清那些曾經嚇壞自己的幻象不過是微風剪影。",
    "potion": "快樂鼠尾草精油 + 拉長石，驅散心靈迷霧，穩固潛意識直覺。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【朧月夜】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_19",
    "name": "XIX. 太陽 (The Sun)",
    "ukiyoName": "天照初日",
    "element": "火",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "金光璀璨普照富士的神聖天照大神，光耀大地萬物復甦，生命力鼎盛歡慶勝利。",
    "reversed": "過度盲目、驕陽炙烤、精力耗盡。適度遮蔭調養生息，避免盛極而驕。",
    "potion": "甜橙精油 + 黃水晶，沐浴在金色暖陽中，綻放純粹自信喜悅。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【天照初日】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_20",
    "name": "XX. 審判 (Judgement)",
    "ukiyoName": "神輿天號",
    "element": "火",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "神鳴太鼓震天動地，喚醒沉睡靈魂，因果結算、第二人生重啟啟程之時。",
    "reversed": "自我苛責、猶豫拖延、錯失轉機。原諒過去無知的自己，放下法槌輕裝跨越。",
    "potion": "白千層精油 + 捷克隕石，震盪沉睡靈魂，開啟嶄新生命天命。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【神輿天號】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_21",
    "name": "XXI. 世界 (The World)",
    "ukiyoName": "萬象圓滿",
    "element": "土",
    "type": "major",
    "symbol": "🎴",
    "hanko": "浮世",
    "upright": "四靈守護天地調和的盛大江戶繪卷，階段性大功告成，四海大通，圓滿昇華。",
    "reversed": "功虧一簣、臨門一腳、拖延結案。集中精力完成最後一哩路，邁向更高螺旋。",
    "potion": "檀香精油 + 鈦晶，統合身心靈頻率，歡慶人生的盛大圓滿。",
    "ukiyoMotif": "江戶浮世繪大師木版畫筆觸，描繪【萬象圓滿】之和風神聖意象，金箔雲紋與波千鳥水紋相映。"
  },
  {
    "id": "t_22",
    "name": "權杖 (Wands) · 首 (Ace)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之首 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 首 (Ace)】：初始源泉、無限潛能、契機萌發。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 首 (Ace)】：開局猶豫、能量受阻、錯失良機。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_23",
    "name": "權杖 (Wands) · 二 (Two)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之二 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 二 (Two)】：平衡抉擇、夥伴合作、籌謀佈局。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 二 (Two)】：兩難矛盾、失衡衝突、猶豫不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_24",
    "name": "權杖 (Wands) · 三 (Three)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之三 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 三 (Three)】：初步成果、團隊協作、擴展遠景。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 三 (Three)】：基礎薄弱、溝通分歧、進展延誤。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_25",
    "name": "權杖 (Wands) · 四 (Four)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之四 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 四 (Four)】：穩固基石、安居守成、界線分明。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 四 (Four)】：固步自封、僵化防衛、停滯不前。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_26",
    "name": "權杖 (Wands) · 五 (Five)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之五 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 五 (Five)】：競爭挑戰、利益角逐、動盪考驗。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 五 (Five)】：內耗紛爭、疲憊退場、自我折損。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_27",
    "name": "權杖 (Wands) · 六 (Six)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之六 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 六 (Six)】：勝利榮耀、互惠分享、平順過渡。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 六 (Six)】：驕傲自滿、依賴成性、暫時受挫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_28",
    "name": "權杖 (Wands) · 七 (Seven)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之七 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 七 (Seven)】：堅持信念、評估抉擇、防禦守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 七 (Seven)】：焦慮懷疑、寡不敵眾、策略失靈。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_29",
    "name": "權杖 (Wands) · 八 (Eight)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之八 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 八 (Eight)】：迅速進展、專注修煉、脫離泥淖。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 八 (Eight)】：急躁冒進、耐心告罄、拖延不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_30",
    "name": "權杖 (Wands) · 九 (Nine)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之九 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 九 (Nine)】：豐盛在握、防線堅固、獨自守望。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 九 (Nine)】：過度防備、疲憊不堪、臨門退縮。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_31",
    "name": "權杖 (Wands) · 十 (Ten)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之十 ",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 十 (Ten)】：盛極大成、承擔重任、循環完結。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 十 (Ten)】：重擔壓垮、強弩之末、責任過荷。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_32",
    "name": "權杖 (Wands) · 侍從 (Page)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之侍從",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 侍從 (Page)】：好學求知、靈活信差、探索熱誠。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 侍從 (Page)】：幼稚任性、消息延遲、缺乏經驗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_33",
    "name": "權杖 (Wands) · 騎士 (Knight)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之騎士",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 騎士 (Knight)】：勇猛奔馳、果敢推進、全力出擊。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 騎士 (Knight)】：魯莽暴衝、耐力不足、方向偏頗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_34",
    "name": "權杖 (Wands) · 王后 (Queen)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之王后",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 王后 (Queen)】：內在滋養、成熟直覺、深層守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 王后 (Queen)】：情緒用事、過度控制、冷漠疏離。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_35",
    "name": "權杖 (Wands) · 國王 (King)",
    "ukiyoName": "和風浮世 · 武士刀與戰旗之國王",
    "element": "火",
    "type": "minor",
    "symbol": "🔥",
    "hanko": "和風",
    "upright": "正位展現【權杖 (Wands) · 國王 (King)】：掌舵掌控、成熟權威、格局顯化。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【權杖 (Wands) · 國王 (King)】：霸道專制、固執死板、威權壓迫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "虎眼石 + 黑胡椒精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_36",
    "name": "聖杯 (Cups) · 首 (Ace)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之首 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 首 (Ace)】：初始源泉、無限潛能、契機萌發。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 首 (Ace)】：開局猶豫、能量受阻、錯失良機。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_37",
    "name": "聖杯 (Cups) · 二 (Two)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之二 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 二 (Two)】：平衡抉擇、夥伴合作、籌謀佈局。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 二 (Two)】：兩難矛盾、失衡衝突、猶豫不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_38",
    "name": "聖杯 (Cups) · 三 (Three)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之三 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 三 (Three)】：初步成果、團隊協作、擴展遠景。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 三 (Three)】：基礎薄弱、溝通分歧、進展延誤。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_39",
    "name": "聖杯 (Cups) · 四 (Four)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之四 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 四 (Four)】：穩固基石、安居守成、界線分明。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 四 (Four)】：固步自封、僵化防衛、停滯不前。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_40",
    "name": "聖杯 (Cups) · 五 (Five)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之五 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 五 (Five)】：競爭挑戰、利益角逐、動盪考驗。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 五 (Five)】：內耗紛爭、疲憊退場、自我折損。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_41",
    "name": "聖杯 (Cups) · 六 (Six)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之六 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 六 (Six)】：勝利榮耀、互惠分享、平順過渡。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 六 (Six)】：驕傲自滿、依賴成性、暫時受挫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_42",
    "name": "聖杯 (Cups) · 七 (Seven)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之七 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 七 (Seven)】：堅持信念、評估抉擇、防禦守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 七 (Seven)】：焦慮懷疑、寡不敵眾、策略失靈。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_43",
    "name": "聖杯 (Cups) · 八 (Eight)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之八 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 八 (Eight)】：迅速進展、專注修煉、脫離泥淖。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 八 (Eight)】：急躁冒進、耐心告罄、拖延不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_44",
    "name": "聖杯 (Cups) · 九 (Nine)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之九 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 九 (Nine)】：豐盛在握、防線堅固、獨自守望。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 九 (Nine)】：過度防備、疲憊不堪、臨門退縮。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_45",
    "name": "聖杯 (Cups) · 十 (Ten)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之十 ",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 十 (Ten)】：盛極大成、承擔重任、循環完結。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 十 (Ten)】：重擔壓垮、強弩之末、責任過荷。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_46",
    "name": "聖杯 (Cups) · 侍從 (Page)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之侍從",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 侍從 (Page)】：好學求知、靈活信差、探索熱誠。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 侍從 (Page)】：幼稚任性、消息延遲、缺乏經驗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_47",
    "name": "聖杯 (Cups) · 騎士 (Knight)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之騎士",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 騎士 (Knight)】：勇猛奔馳、果敢推進、全力出擊。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 騎士 (Knight)】：魯莽暴衝、耐力不足、方向偏頗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_48",
    "name": "聖杯 (Cups) · 王后 (Queen)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之王后",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 王后 (Queen)】：內在滋養、成熟直覺、深層守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 王后 (Queen)】：情緒用事、過度控制、冷漠疏離。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_49",
    "name": "聖杯 (Cups) · 國王 (King)",
    "ukiyoName": "和風浮世 · 金繕朱漆酒器之國王",
    "element": "水",
    "type": "minor",
    "symbol": "🌊",
    "hanko": "和風",
    "upright": "正位展現【聖杯 (Cups) · 國王 (King)】：掌舵掌控、成熟權威、格局顯化。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【聖杯 (Cups) · 國王 (King)】：霸道專制、固執死板、威權壓迫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "海藍寶 + 玫瑰精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_50",
    "name": "寶劍 (Swords) · 首 (Ace)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之首 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 首 (Ace)】：初始源泉、無限潛能、契機萌發。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 首 (Ace)】：開局猶豫、能量受阻、錯失良機。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_51",
    "name": "寶劍 (Swords) · 二 (Two)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之二 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 二 (Two)】：平衡抉擇、夥伴合作、籌謀佈局。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 二 (Two)】：兩難矛盾、失衡衝突、猶豫不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_52",
    "name": "寶劍 (Swords) · 三 (Three)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之三 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 三 (Three)】：初步成果、團隊協作、擴展遠景。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 三 (Three)】：基礎薄弱、溝通分歧、進展延誤。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_53",
    "name": "寶劍 (Swords) · 四 (Four)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之四 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 四 (Four)】：穩固基石、安居守成、界線分明。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 四 (Four)】：固步自封、僵化防衛、停滯不前。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_54",
    "name": "寶劍 (Swords) · 五 (Five)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之五 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 五 (Five)】：競爭挑戰、利益角逐、動盪考驗。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 五 (Five)】：內耗紛爭、疲憊退場、自我折損。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_55",
    "name": "寶劍 (Swords) · 六 (Six)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之六 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 六 (Six)】：勝利榮耀、互惠分享、平順過渡。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 六 (Six)】：驕傲自滿、依賴成性、暫時受挫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_56",
    "name": "寶劍 (Swords) · 七 (Seven)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之七 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 七 (Seven)】：堅持信念、評估抉擇、防禦守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 七 (Seven)】：焦慮懷疑、寡不敵眾、策略失靈。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_57",
    "name": "寶劍 (Swords) · 八 (Eight)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之八 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 八 (Eight)】：迅速進展、專注修煉、脫離泥淖。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 八 (Eight)】：急躁冒進、耐心告罄、拖延不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_58",
    "name": "寶劍 (Swords) · 九 (Nine)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之九 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 九 (Nine)】：豐盛在握、防線堅固、獨自守望。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 九 (Nine)】：過度防備、疲憊不堪、臨門退縮。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_59",
    "name": "寶劍 (Swords) · 十 (Ten)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之十 ",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 十 (Ten)】：盛極大成、承擔重任、循環完結。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 十 (Ten)】：重擔壓垮、強弩之末、責任過荷。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_60",
    "name": "寶劍 (Swords) · 侍從 (Page)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之侍從",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 侍從 (Page)】：好學求知、靈活信差、探索熱誠。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 侍從 (Page)】：幼稚任性、消息延遲、缺乏經驗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_61",
    "name": "寶劍 (Swords) · 騎士 (Knight)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之騎士",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 騎士 (Knight)】：勇猛奔馳、果敢推進、全力出擊。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 騎士 (Knight)】：魯莽暴衝、耐力不足、方向偏頗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_62",
    "name": "寶劍 (Swords) · 王后 (Queen)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之王后",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 王后 (Queen)】：內在滋養、成熟直覺、深層守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 王后 (Queen)】：情緒用事、過度控制、冷漠疏離。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_63",
    "name": "寶劍 (Swords) · 國王 (King)",
    "ukiyoName": "和風浮世 · 淬鍊名刀切物之國王",
    "element": "風",
    "type": "minor",
    "symbol": "⚔️",
    "hanko": "和風",
    "upright": "正位展現【寶劍 (Swords) · 國王 (King)】：掌舵掌控、成熟權威、格局顯化。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【寶劍 (Swords) · 國王 (King)】：霸道專制、固執死板、威權壓迫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "青金石 + 薄荷精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_64",
    "name": "錢幣 (Pentacles) · 首 (Ace)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之首 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 首 (Ace)】：初始源泉、無限潛能、契機萌發。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 首 (Ace)】：開局猶豫、能量受阻、錯失良機。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_65",
    "name": "錢幣 (Pentacles) · 二 (Two)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之二 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 二 (Two)】：平衡抉擇、夥伴合作、籌謀佈局。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 二 (Two)】：兩難矛盾、失衡衝突、猶豫不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_66",
    "name": "錢幣 (Pentacles) · 三 (Three)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之三 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 三 (Three)】：初步成果、團隊協作、擴展遠景。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 三 (Three)】：基礎薄弱、溝通分歧、進展延誤。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_67",
    "name": "錢幣 (Pentacles) · 四 (Four)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之四 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 四 (Four)】：穩固基石、安居守成、界線分明。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 四 (Four)】：固步自封、僵化防衛、停滯不前。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_68",
    "name": "錢幣 (Pentacles) · 五 (Five)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之五 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 五 (Five)】：競爭挑戰、利益角逐、動盪考驗。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 五 (Five)】：內耗紛爭、疲憊退場、自我折損。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_69",
    "name": "錢幣 (Pentacles) · 六 (Six)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之六 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 六 (Six)】：勝利榮耀、互惠分享、平順過渡。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 六 (Six)】：驕傲自滿、依賴成性、暫時受挫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_70",
    "name": "錢幣 (Pentacles) · 七 (Seven)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之七 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 七 (Seven)】：堅持信念、評估抉擇、防禦守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 七 (Seven)】：焦慮懷疑、寡不敵眾、策略失靈。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_71",
    "name": "錢幣 (Pentacles) · 八 (Eight)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之八 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 八 (Eight)】：迅速進展、專注修煉、脫離泥淖。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 八 (Eight)】：急躁冒進、耐心告罄、拖延不決。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_72",
    "name": "錢幣 (Pentacles) · 九 (Nine)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之九 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 九 (Nine)】：豐盛在握、防線堅固、獨自守望。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 九 (Nine)】：過度防備、疲憊不堪、臨門退縮。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_73",
    "name": "錢幣 (Pentacles) · 十 (Ten)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之十 ",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 十 (Ten)】：盛極大成、承擔重任、循環完結。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 十 (Ten)】：重擔壓垮、強弩之末、責任過荷。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_74",
    "name": "錢幣 (Pentacles) · 侍從 (Page)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之侍從",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 侍從 (Page)】：好學求知、靈活信差、探索熱誠。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 侍從 (Page)】：幼稚任性、消息延遲、缺乏經驗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_75",
    "name": "錢幣 (Pentacles) · 騎士 (Knight)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之騎士",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 騎士 (Knight)】：勇猛奔馳、果敢推進、全力出擊。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 騎士 (Knight)】：魯莽暴衝、耐力不足、方向偏頗。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_76",
    "name": "錢幣 (Pentacles) · 王后 (Queen)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之王后",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 王后 (Queen)】：內在滋養、成熟直覺、深層守護。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 王后 (Queen)】：情緒用事、過度控制、冷漠疏離。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  },
  {
    "id": "t_77",
    "name": "錢幣 (Pentacles) · 國王 (King)",
    "ukiyoName": "和風浮世 · 江戶金幣小判之國王",
    "element": "土",
    "type": "minor",
    "symbol": "🪙",
    "hanko": "和風",
    "upright": "正位展現【錢幣 (Pentacles) · 國王 (King)】：掌舵掌控、成熟權威、格局顯化。對準當前能量，以積極正向姿態推進。",
    "reversed": "逆位提醒【錢幣 (Pentacles) · 國王 (King)】：霸道專制、固執死板、威權壓迫。宜放慢步調進行深度盤點，防範暗礁。",
    "potion": "黃水晶 + 雪松精油",
    "ukiyoMotif": "江戶浮世繪木版畫刻繪，背景為傳統浮世青海波紋飾與金箔點綴。"
  }
];
  const LENORMAND_CARDS = [
  {
    "num": 1,
    "name": "01 騎士 (Rider)",
    "ukiyoName": "飛腳快馬",
    "pips": "紅心 9",
    "symbol": "🏇",
    "hanko": "浮世",
    "desc": "東海道驛站之飛腳快馬馳騁送達吉信，快速突破現狀。",
    "potion": "甜橙精油 + 白水晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【飛腳快馬】。"
  },
  {
    "num": 2,
    "name": "02 幸運草 (Clover)",
    "ukiyoName": "春野四葉",
    "pips": "方塊 6",
    "symbol": "🍀",
    "hanko": "浮世",
    "desc": "江戶春郊草甸之幸運四葉，帶來短暫而驚喜的小確幸。",
    "potion": "薄荷精油 + 綠幽靈",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【春野四葉】。"
  },
  {
    "num": 3,
    "name": "03 船 (Ship)",
    "ukiyoName": "千石商船",
    "pips": "黑桃 10",
    "symbol": "⛵",
    "hanko": "浮世",
    "desc": "揚起風帆乘風破浪之千石船，象徵遠行貿易與志向開拓。",
    "potion": "迷迭香精油 + 青金石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【千石商船】。"
  },
  {
    "num": 4,
    "name": "04 房屋 (House)",
    "ukiyoName": "町屋茶室",
    "pips": "紅心 K",
    "symbol": "🏡",
    "hanko": "浮世",
    "desc": "暖簾遮掩之雅致町屋，代表心靈安住、家族庇蔭與踏實根基。",
    "potion": "雪松精油 + 茶晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【町屋茶室】。"
  },
  {
    "num": 5,
    "name": "05 樹 (Tree)",
    "ukiyoName": "千年神木",
    "pips": "紅心 7",
    "symbol": "🌳",
    "hanko": "浮世",
    "desc": "神社參道之千年巨杉，長壽扎根、身心療癒、歲月滋養。",
    "potion": "絲柏精油 + 綠東陵",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【千年神木】。"
  },
  {
    "num": 6,
    "name": "06 雲 (Clouds)",
    "ukiyoName": "煙雨微嵐",
    "pips": "梅花 K",
    "symbol": "☁️",
    "hanko": "浮世",
    "desc": "富士山腰之浮雲迷霧，暫時遮蔽前路，耐心等待天晴霧散。",
    "potion": "尤加利精油 + 螢石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【煙雨微嵐】。"
  },
  {
    "num": 7,
    "name": "07 蛇 (Snake)",
    "ukiyoName": "白蛇仙靈",
    "pips": "梅花 Q",
    "symbol": "🐍",
    "hanko": "浮世",
    "desc": "竹林蜿蜒之靈蛇，象徵曲折迂迴、危機洞察與智慧蛻變。",
    "potion": "真正薰衣草 + 黑曜石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【白蛇仙靈】。"
  },
  {
    "num": 8,
    "name": "08 棺材 (Coffin)",
    "ukiyoName": "落葉歸土",
    "pips": "方塊 9",
    "symbol": "⚰️",
    "hanko": "浮世",
    "desc": "空寂古寺之落櫻塵封，重大終結不可逆，歸零方得大生。",
    "potion": "沒藥精油 + 透石膏",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【落葉歸土】。"
  },
  {
    "num": 9,
    "name": "09 花束 (Bouquet)",
    "ukiyoName": "友禪花束",
    "pips": "黑桃 Q",
    "symbol": "💐",
    "hanko": "浮世",
    "desc": "友禪染花紋般精美之時令花禮，社交禮讚與喜慶賞賜。",
    "potion": "玫瑰精油 + 粉晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【友禪花束】。"
  },
  {
    "num": 10,
    "name": "10 鐮刀 (Scythe)",
    "ukiyoName": "秋收名鐮",
    "pips": "方塊 J",
    "symbol": "🌾",
    "hanko": "浮世",
    "desc": "秋分收割之銳利神鐮，快刀斬亂麻，果斷切割斷捨離。",
    "potion": "黑胡椒精油 + 赤鐵礦",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【秋收名鐮】。"
  },
  {
    "num": 11,
    "name": "11 鞭子 (Whip)",
    "ukiyoName": "武術竹刀",
    "pips": "梅花 J",
    "symbol": "🪢",
    "hanko": "浮世",
    "desc": "道場揮汗對擊之竹刀，象徵反覆修煉、摩擦磨合與耐力考驗。",
    "potion": "肉桂精油 + 紅石榴",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【武術竹刀】。"
  },
  {
    "num": 12,
    "name": "12 鳥 (Birds)",
    "ukiyoName": "林間喜鵲",
    "pips": "方塊 7",
    "symbol": "🐦",
    "hanko": "浮世",
    "desc": "古木枝頭熱烈歡鳴之雙鳥，熱絡通訊、商討磋商、資訊交會。",
    "potion": "佛手柑精油 + 藍紋瑪瑙",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【林間喜鵲】。"
  },
  {
    "num": 13,
    "name": "13 小孩 (Child)",
    "ukiyoName": "赤子童趣",
    "pips": "黑桃 J",
    "symbol": "👶",
    "hanko": "浮世",
    "desc": "江戶街道捉迷藏之稚童，象徵純真初創、微型項目與探索好奇。",
    "potion": "甜橙精油 + 白水晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【赤子童趣】。"
  },
  {
    "num": 14,
    "name": "14 狐狸 (Fox)",
    "ukiyoName": "稻荷靈狐",
    "pips": "梅花 9",
    "symbol": "🦊",
    "hanko": "浮世",
    "desc": "稻荷神社聰敏之神使白狐，代表職場精明謀略與防範小人。",
    "potion": "乳香精油 + 虎眼石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【稻荷靈狐】。"
  },
  {
    "num": 15,
    "name": "15 熊 (Bear)",
    "ukiyoName": "山野金熊",
    "pips": "梅花 10",
    "symbol": "🐻",
    "hanko": "浮世",
    "desc": "深山氣勢沉雄之巨熊，雄厚財富底氣、權力庇護與堅強靠山。",
    "potion": "岩蘭草精油 + 黃水晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【山野金熊】。"
  },
  {
    "num": 16,
    "name": "16 星星 (Stars)",
    "ukiyoName": "天河明宿",
    "pips": "紅心 6",
    "symbol": "⭐",
    "hanko": "浮世",
    "desc": "清澈夜空漫天繁星，照亮航海征途，崇高天命與靈魂願景。",
    "potion": "橙花精油 + 天河石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【天河明宿】。"
  },
  {
    "num": 17,
    "name": "17 鸛鳥 (Stork)",
    "ukiyoName": "白鶴翔空",
    "pips": "紅心 Q",
    "symbol": "🪶",
    "hanko": "浮世",
    "desc": "乘祥雲翱翔之靈鶴，象徵喬遷進階、環境革新與良善循環。",
    "potion": "玫瑰草精油 + 海藍寶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【白鶴翔空】。"
  },
  {
    "num": 18,
    "name": "18 狗 (Dog)",
    "ukiyoName": "忠犬柴犬",
    "pips": "紅心 10",
    "symbol": "🐕",
    "hanko": "浮世",
    "desc": "忠誠守護家門之日本柴犬，至死不渝之摯友盟誼與信任託付。",
    "potion": "洋甘菊精油 + 綠松石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【忠犬柴犬】。"
  },
  {
    "num": 19,
    "name": "19 塔 (Tower)",
    "ukiyoName": "天守高閣",
    "pips": "黑桃 6",
    "symbol": "🏰",
    "hanko": "浮世",
    "desc": "高聳雲霄之石垣天守閣，官方體制、權力中樞與獨善其身。",
    "potion": "雪松精油 + 煙晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【天守高閣】。"
  },
  {
    "num": 20,
    "name": "20 花園 (Garden)",
    "ukiyoName": "大名庭園",
    "pips": "黑桃 8",
    "symbol": "⛲",
    "hanko": "浮世",
    "desc": "迴游式枯山水大名庭園，名流聚會、社交圈拓展與公開發表。",
    "potion": "天竺葵精油 + 紫水晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【大名庭園】。"
  },
  {
    "num": 21,
    "name": "21 山 (Mountain)",
    "ukiyoName": "富嶽雪峰",
    "pips": "梅花 8",
    "symbol": "⛰️",
    "hanko": "浮世",
    "desc": "白雪皚皚之富士靈峰，巍峨阻隔、不可撼動之耐心修煉考驗。",
    "potion": "乳香精油 + 瑪瑙",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【富嶽雪峰】。"
  },
  {
    "num": 22,
    "name": "22 十字路口 (Crossroad)",
    "ukiyoName": "宿場岔道",
    "pips": "方塊 Q",
    "symbol": "🔀",
    "hanko": "浮世",
    "desc": "東海道與中山道交匯之岔路口，多方權衡抉擇與命運岔路。",
    "potion": "薄荷精油 + 螢石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【宿場岔道】。"
  },
  {
    "num": 23,
    "name": "23 老鼠 (Mice)",
    "ukiyoName": "米倉耗鼠",
    "pips": "梅花 7",
    "symbol": "🐁",
    "hanko": "浮世",
    "desc": "米倉角落啃蝕之小鼠，象徵日常微小漏財、體力精力悄然損耗。",
    "potion": "茶樹精油 + 黑曜石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【米倉耗鼠】。"
  },
  {
    "num": 24,
    "name": "24 心 (Heart)",
    "ukiyoName": "真心赤誠",
    "pips": "紅心 J",
    "symbol": "❤️",
    "hanko": "浮世",
    "desc": "朱漆雕刻之赤誠之心，純真愛戀、深厚熱情與靈魂共鳴。",
    "potion": "大馬士革玫瑰 + 菱錳礦",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【真心赤誠】。"
  },
  {
    "num": 25,
    "name": "25 戒指 (Ring)",
    "ukiyoName": "金鈿結繩",
    "pips": "梅花 A",
    "symbol": "💍",
    "hanko": "浮世",
    "desc": "結緣御守之五色金鈿繩，神聖誓約、合同簽訂與長期夥伴同盟。",
    "potion": "檀香精油 + 鈦晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【金鈿結繩】。"
  },
  {
    "num": 26,
    "name": "26 書 (Book)",
    "ukiyoName": "秘卷經匣",
    "pips": "方塊 10",
    "symbol": "📖",
    "hanko": "浮世",
    "desc": "藏於密室之古卷手抄秘典，深層知識、未揭密辛與專門研讀。",
    "potion": "迷迭香精油 + 青金石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【秘卷經匣】。"
  },
  {
    "num": 27,
    "name": "27 信 (Letter)",
    "ukiyoName": "和紙書簡",
    "pips": "黑桃 7",
    "symbol": "✉️",
    "hanko": "浮世",
    "desc": "以毛筆墨跡寫就之和紙書簡，正式通牒、契約文書與訊息傳遞。",
    "potion": "尤加利精油 + 白水晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【和紙書簡】。"
  },
  {
    "num": 28,
    "name": "28 男人 (Gentleman)",
    "ukiyoName": "武士郎君",
    "pips": "紅心 A",
    "symbol": "👨",
    "hanko": "浮世",
    "desc": "英氣挺拔之年輕武士，陽性能量焦點、主動推進者與男性貴人。",
    "potion": "黑胡椒精油 + 太陽石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【武士郎君】。"
  },
  {
    "num": 29,
    "name": "29 女人 (Lady)",
    "ukiyoName": "和服淑媛",
    "pips": "黑桃 A",
    "symbol": "👩",
    "hanko": "浮世",
    "desc": "溫婉嫻雅之和服淑媛，陰性能量焦點、包容滋養者與女性貴人。",
    "potion": "依蘭精油 + 月光石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【和服淑媛】。"
  },
  {
    "num": 30,
    "name": "30 百合 (Lily)",
    "ukiyoName": "清幽幽蘭",
    "pips": "黑桃 K",
    "symbol": "⚜️",
    "hanko": "浮世",
    "desc": "石階旁靜默吐蕊之百合，高雅品格、長者智德與清白福分。",
    "potion": "真正薰衣草 + 透石膏",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【清幽幽蘭】。"
  },
  {
    "num": 31,
    "name": "31 太陽 (Sun)",
    "ukiyoName": "旭日東昇",
    "pips": "方塊 A",
    "symbol": "☀️",
    "hanko": "浮世",
    "desc": "江戶灣上破曉之旭日初升，萬道金芒、驅散陰暗之絕對吉慶。",
    "potion": "甜橙精油 + 黃水晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【旭日東昇】。"
  },
  {
    "num": 32,
    "name": "32 月亮 (Moon)",
    "ukiyoName": "滿月夜景",
    "pips": "紅心 8",
    "symbol": "🌙",
    "hanko": "浮世",
    "desc": "金箔映襯之盛大滿月，藝術才華、名利聲望與靈性直覺潮起。",
    "potion": "茉莉精油 + 月光石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【滿月夜景】。"
  },
  {
    "num": 33,
    "name": "33 鑰匙 (Key)",
    "ukiyoName": "黃金寶鑰",
    "pips": "方塊 8",
    "symbol": "🗝️",
    "hanko": "浮世",
    "desc": "開啟密藏寶閣之黃金神匙，豁然開朗、關鍵解方就在眼前。",
    "potion": "檸檬精油 + 虎眼石",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【黃金寶鑰】。"
  },
  {
    "num": 34,
    "name": "34 魚 (Fish)",
    "ukiyoName": "江戶錦鯉",
    "pips": "方塊 K",
    "symbol": "🐟",
    "hanko": "浮世",
    "desc": "清泉池中躍動之七彩錦鯉，源源不絕之商賈金流與豐饒富貴。",
    "potion": "肉桂精油 + 金髮晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【江戶錦鯉】。"
  },
  {
    "num": 35,
    "name": "35 錨 (Anchor)",
    "ukiyoName": "鐵鑄定錨",
    "pips": "黑桃 9",
    "symbol": "⚓",
    "hanko": "浮世",
    "desc": "海港深定之玄鐵巨錨，風浪平息、長治久安、終身安身立命。",
    "potion": "雪松精油 + 赤鐵礦",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【鐵鑄定錨】。"
  },
  {
    "num": 36,
    "name": "36 十字架 (Cross)",
    "ukiyoName": "靈魂試煉",
    "pips": "梅花 6",
    "symbol": "✝️",
    "hanko": "浮世",
    "desc": "風雨洗禮之靈性十字碑，靈魂神聖功課、承擔重負後的昇華轉化。",
    "potion": "乳香精油 + 紫水晶",
    "ukiyoMotif": "江戶浮世繪版畫風格，木刻刀法細膩，配以和紙肌理與朱印【靈魂試煉】。"
  }
];

  const xmlEscape = value => String(value || '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));

  /**
   * 為全部塔羅與雷諾曼牌產生獨立的內嵌 Ukiyo-e 木版畫。
   * 每張牌以名稱雜湊建立不同構圖、印色與印章位置，保留一套一致的江戶畫冊語言。
   */
  function renderUkiyoeArt(card, system) {
    const title = String(card.name || '神諭牌');
    const seed = [...title].reduce((sum, char) => sum + char.codePointAt(0), system === 'tarot' ? 17 : 47);
    const hue = seed % 2 ? '#173a5e' : '#294d42';
    const accent = seed % 3 ? '#b8412e' : '#c9973e';
    const isTarot = system === 'tarot';
    const motifText = `${title} ${card.ukiyoName || ''}`;
    let motif = '';
    if (/權杖|Wands|鞭子|鐮刀/.test(motifText)) motif = '<path d="M88 162L153 70M113 171L176 82" stroke="#5b301e" stroke-width="10" stroke-linecap="round"/><path d="M87 162L153 70M113 171L176 82" stroke="#d9b45e" stroke-width="3" stroke-linecap="round"/>';
    else if (/寶劍|Swords|劍|鞭子/.test(motifText)) motif = '<path d="M132 178L132 72M111 95L153 95M121 72L132 53L143 72" stroke="#35414a" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><path d="M132 172L132 78" stroke="#e7edf0" stroke-width="3"/>';
    else if (/聖杯|Cups|心|花束/.test(motifText)) motif = '<path d="M96 86H168L158 132Q132 148 106 132Z" fill="#b94134" stroke="#6e261e" stroke-width="4"/><path d="M132 146V166M106 170H158" stroke="#6e261e" stroke-width="6" stroke-linecap="round"/><path d="M104 95Q132 112 160 95" fill="none" stroke="#efcc76" stroke-width="4"/>';
    else if (/錢幣|Pentacles|金幣|魚|鑰匙/.test(motifText)) motif = '<g fill="#d7a83d" stroke="#795b21" stroke-width="4"><circle cx="108" cy="112" r="26"/><circle cx="157" cy="137" r="28"/><circle cx="146" cy="86" r="22"/></g><g fill="none" stroke="#fff0aa" stroke-width="3"><path d="M108 96v32M92 112h32M146 71v30M131 86h30"/></g>';
    else if (/山|塔|富士|船|雲/.test(motifText)) motif = '<path d="M65 169L124 84L172 169Z" fill="#36566d"/><path d="M104 113L124 84L143 115L132 109L122 119Z" fill="#f8f2df"/><path d="M52 171H205" stroke="#26455b" stroke-width="9"/><path d="M54 183Q78 166 102 183T150 183T202 183" fill="none" stroke="#d9eced" stroke-width="5"/>';
    else if (/太陽|星星|月亮|Stars/.test(motifText)) motif = '<circle cx="132" cy="110" r="37" fill="#e6bb45"/><path d="M132 53v14M132 153v14M75 110h14M175 110h14M92 70l10 10M162 140l10 10M172 70l-10 10M102 140l-10 10" stroke="#d49130" stroke-width="6" stroke-linecap="round"/>';
    else if (/鳥|鸛|狗|狐狸|熊|蛇/.test(motifText)) motif = '<path d="M92 154Q87 106 125 91Q160 78 174 118Q160 153 128 157Q107 158 92 154Z" fill="#d2a545" stroke="#69472b" stroke-width="4"/><circle cx="150" cy="111" r="4" fill="#1e293b"/><path d="M172 119l22 9-22 8" fill="#b94134"/>';
    else motif = '<path d="M72 155V112Q72 84 101 84Q118 84 132 101Q146 84 163 84Q192 84 192 112V155" fill="none" stroke="#b8412e" stroke-width="13" stroke-linecap="round"/><path d="M80 162H184" stroke="#c9973e" stroke-width="7" stroke-linecap="round"/>';

    const blossoms = Array.from({ length: 7 }, (_, i) => {
      const x = 42 + ((seed * (i + 3)) % 188);
      const y = 42 + ((seed * (i + 7)) % 120);
      return `<g transform="translate(${x} ${y})" fill="#e9a4a6"><circle cx="0" cy="-4" r="4"/><circle cx="4" cy="0" r="4"/><circle cx="0" cy="4" r="4"/><circle cx="-4" cy="0" r="4"/><circle r="2.2" fill="#d28a39"/></g>`;
    }).join('');
    const number = isTarot ? String(seed % 78 + 1).padStart(2, '0') : String(card.num || seed % 36 + 1).padStart(2, '0');
    return `<svg viewBox="0 0 264 370" class="ukiyoe-art" role="img" aria-label="${xmlEscape(title)} 浮世繪木版畫"><defs><pattern id="wave-${seed}" width="22" height="14" patternUnits="userSpaceOnUse"><path d="M0 8q5-9 11 0q5 9 11 0" fill="none" stroke="#d7e5e1" stroke-width="1.5"/></pattern><filter id="paper-${seed}"><feTurbulence baseFrequency=".65" numOctaves="2" stitchTiles="stitch" type="fractalNoise"/><feColorMatrix values="1 0 0 0 .8 0 1 0 0 .75 0 0 1 0 .55 0 0 0 .11 0"/></filter></defs><rect width="264" height="370" fill="#f7f0dd"/><rect x="10" y="10" width="244" height="350" rx="4" fill="${hue}"/><rect x="18" y="18" width="228" height="334" fill="url(#wave-${seed})" opacity=".5"/><rect x="18" y="18" width="228" height="334" filter="url(#paper-${seed})" opacity=".45"/><path d="M18 226Q55 202 91 226T164 226T246 226V352H18Z" fill="#315e78" opacity=".9"/>${blossoms}<path d="M28 56Q75 34 118 59Q162 29 234 57" fill="none" stroke="#edd8a1" stroke-width="8" stroke-linecap="round" opacity=".9"/>${motif}<rect x="28" y="286" width="208" height="47" rx="3" fill="#f7f0dd" opacity=".93"/><text x="132" y="307" text-anchor="middle" fill="#253229" font-size="13" font-weight="700" font-family="Noto Serif TC, serif">${xmlEscape(title.slice(0, 18))}</text><text x="132" y="324" text-anchor="middle" fill="#806228" font-size="9" font-family="Noto Serif TC, serif">${xmlEscape(card.ukiyoName || '浮世神諭')}</text><rect x="203" y="34" width="27" height="27" fill="${accent}"/><text x="216" y="53" text-anchor="middle" fill="#fff7de" font-size="12" font-weight="900">${number}</text><rect x="10" y="10" width="244" height="350" rx="4" fill="none" stroke="#c9973e" stroke-width="4"/></svg>`;
  }

  global.MeetJoyDivination = {
    TAROT_CARDS,
    LENORMAND_CARDS,
    renderUkiyoeArt
  };

})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
